MenuItem_driver:  MenuItem_driver.o MenuItem.o
	g++ -g -Wall -std=c++11 -o MenuItem_driver MenuItem.o MenuItem_driver.o

MenuItem_driver.o:  MenuItem_driver.cpp MenuItem.h
	g++ -g -Wall -std=c++11 -c MenuItem_driver.cpp

MenuItem.o:  MenuItem.cpp MenuItem.h
	g++ -g -Wall -std=c++11 -c MenuItem.cpp
