StarTrekDVDdriver:   StarTrekDVDdriver.o StarTrekDVD.o DVD.o
	g++ -g -Wall -std=c++11 -o StarTrekDVDdriver StarTrekDVD.o StarTrekDVDdriver.o DVD.o

StarTrekDVD.o:  StarTrekDVD.cpp StarTrekDVD.h DVD.h
	g++ -g -Wall -std=c++11 -c StarTrekDVD.cpp

StarTrekDVDdriver.o:  StarTrekDVD.cpp StarTrekDVD.h DVD.h
	g++ -g -Wall -std=c++11 -c StarTrekDVDdriver.cpp

DVD.o:  DVD.cpp DVD.h
	g++ -g -Wall -std=c++11 -c DVD.cpp
